var wms_layers = [];


        var lyr_OpenStreetMap_0 = new ol.layer.Tile({
            'title': 'OpenStreetMap',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_ADMINISTRASIKECAMATAN_AR_50K_1 = new ol.format.GeoJSON();
var features_ADMINISTRASIKECAMATAN_AR_50K_1 = format_ADMINISTRASIKECAMATAN_AR_50K_1.readFeatures(json_ADMINISTRASIKECAMATAN_AR_50K_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_ADMINISTRASIKECAMATAN_AR_50K_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_ADMINISTRASIKECAMATAN_AR_50K_1.addFeatures(features_ADMINISTRASIKECAMATAN_AR_50K_1);
var lyr_ADMINISTRASIKECAMATAN_AR_50K_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_ADMINISTRASIKECAMATAN_AR_50K_1, 
                style: style_ADMINISTRASIKECAMATAN_AR_50K_1,
                popuplayertitle: "ADMINISTRASIKECAMATAN_AR_50K",
                interactive: true,
    title: 'ADMINISTRASIKECAMATAN_AR_50K<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_0.png" /> AMAHAI<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_1.png" /> KOTAMASOHI<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_2.png" /> LEIHITU<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_3.png" /> LEIHITU BARAT<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_4.png" /> NUSALAUT<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_5.png" /> PULAU AY<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_6.png" /> PULAU BANDA BESAR<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_7.png" /> PULAU GUNUNGAPI<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_8.png" /> PULAU HATTA<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_9.png" /> PULAU KARAKA<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_10.png" /> PULAU NAILAKA<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_11.png" /> PULAU NEIRA<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_12.png" /> PULAU RHUN<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_13.png" /> PULAU SYAHRIR<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_14.png" /> PULAUHARUKU<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_15.png" /> SALAHUTU<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_16.png" /> SAPARUA<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_17.png" /> SERAM UTARA<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_18.png" /> SERAM UTARA BARAT<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_19.png" /> TANIWEL<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_20.png" /> TEHORU<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_21.png" /> TELUKAMBON<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_22.png" /> TELUKELPAPUTIH<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_23.png" /> TEON NILA SERUA<br />\
    <img src="styles/legend/ADMINISTRASIKECAMATAN_AR_50K_1_24.png" /> TEONNILASERUA<br />'
        });
var format_SARANAIBADAH_PT_50K_2 = new ol.format.GeoJSON();
var features_SARANAIBADAH_PT_50K_2 = format_SARANAIBADAH_PT_50K_2.readFeatures(json_SARANAIBADAH_PT_50K_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_SARANAIBADAH_PT_50K_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_SARANAIBADAH_PT_50K_2.addFeatures(features_SARANAIBADAH_PT_50K_2);
var lyr_SARANAIBADAH_PT_50K_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_SARANAIBADAH_PT_50K_2, 
                style: style_SARANAIBADAH_PT_50K_2,
                popuplayertitle: "SARANAIBADAH_PT_50K",
                interactive: true,
    title: 'SARANAIBADAH_PT_50K<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_0.png" /> Gereja Kecamatan Amahai<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_1.png" /> Gereja Kecamatan Kotamasohi<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_2.png" /> Gereja Kecamatan Leihitu Barat<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_3.png" /> Gereja Kecamatan Nusalaut<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_4.png" /> Gereja Kecamatan Pulauharuku<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_5.png" /> Gereja Kecamatan Salahutu<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_6.png" /> Gereja Kecamatan Saparua<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_7.png" /> Gereja Kecamatan Seram Utara<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_8.png" /> Gereja Kecamatan Seram Utara Barat<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_9.png" /> Gereja Kecamatan Tehoru<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_10.png" /> Gereja Kecamatan Telukelpaputih<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_11.png" /> Gereja Kecamatan Teonnilaserua<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_12.png" /> Gereja Kecamatan Utara Barat<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_13.png" /> Masjid Kecamatan Amahai<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_14.png" /> Masjid Kecamatan Kotamasohi<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_15.png" /> Masjid Kecamatan Leihitu<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_16.png" /> Masjid Kecamatan Leihitu Barat<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_17.png" /> Masjid Kecamatan Pulauharuku<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_18.png" /> Masjid Kecamatan Salahutu<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_19.png" /> Masjid Kecamatan Saparua<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_20.png" /> Masjid Kecamatan Seram Utara<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_21.png" /> Masjid Kecamatan Seram Utara Barat<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_22.png" /> Masjid Kecamatan Tehoru<br />\
    <img src="styles/legend/SARANAIBADAH_PT_50K_2_23.png" /> Pura Kecamatan Seram Utara<br />'
        });
var format_SUNGAI_LN_50K_3 = new ol.format.GeoJSON();
var features_SUNGAI_LN_50K_3 = format_SUNGAI_LN_50K_3.readFeatures(json_SUNGAI_LN_50K_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_SUNGAI_LN_50K_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_SUNGAI_LN_50K_3.addFeatures(features_SUNGAI_LN_50K_3);
var lyr_SUNGAI_LN_50K_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_SUNGAI_LN_50K_3, 
                style: style_SUNGAI_LN_50K_3,
                popuplayertitle: "SUNGAI_LN_50K",
                interactive: true,
    title: 'SUNGAI_LN_50K<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_0.png" /> Wai  Era<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_1.png" /> Wai  Lalan<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_2.png" /> Wai Abas<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_3.png" /> Wai Abubu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_4.png" /> Wai Aipate<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_5.png" /> Wai Airbuaya<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_6.png" /> Wai Akoon<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_7.png" /> Wai Alahaal<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_8.png" /> Wai Alala<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_9.png" /> Wai Alau<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_10.png" /> Wai Alpautu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_11.png" /> Wai Alui<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_12.png" /> Wai Aotin<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_13.png" /> Wai Arisasu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_14.png" /> Wai Aritolaka<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_15.png" /> Wai Aru<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_16.png" /> Wai Asala<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_17.png" /> Wai Aseli<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_18.png" /> Wai Asih<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_19.png" /> Wai Asimala<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_20.png" /> Wai Asinahu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_21.png" /> Wai Ata<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_22.png" /> Wai Atamuluno<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_23.png" /> Wai Atauluhtu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_24.png" /> Wai Au<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_25.png" /> Wai Aun<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_26.png" /> Wai Awa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_27.png" /> Wai Baba<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_28.png" /> Wai Bafahtol<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_29.png" /> Wai Baruno<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_30.png" /> Wai Batekano<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_31.png" /> Wai Batuitam<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_32.png" /> Wai Batukabira<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_33.png" /> Wai Batulayang<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_34.png" /> Wai Belaraitira<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_35.png" /> Wai Besar<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_36.png" /> Wai Besar Satu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_37.png" /> Wai Binai<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_38.png" /> Wai Bonara<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_39.png" /> Wai Boti<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_40.png" /> Wai Boyan<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_41.png" /> Wai Damai<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_42.png" /> Wai Dhtuno<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_43.png" /> Wai Dinai<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_44.png" /> Wai Dinua<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_45.png" /> Wai Dulaka<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_46.png" /> Wai Ela<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_47.png" /> Wai Ele<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_48.png" /> Wai Elelei<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_49.png" /> Wai Eleuw<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_50.png" /> Wai Ema<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_51.png" /> Wai Enau<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_52.png" /> Wai Epu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_53.png" /> Wai Ete<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_54.png" /> Wai Eya<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_55.png" /> Wai Fatuina<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_56.png" /> Wai Film<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_57.png" /> Wai Fuhma<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_58.png" /> Wai Funala<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_59.png" /> Wai Hairisa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_60.png" /> Wai Hakasina<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_61.png" /> Wai Halawato<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_62.png" /> Wai Halong<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_63.png" /> Wai Haru<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_64.png" /> Wai Haruru<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_65.png" /> Wai Hatu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_66.png" /> Wai Hatunau<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_67.png" /> Wai Hatupia<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_68.png" /> Wai Hatuputih<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_69.png" /> Wai Hauso<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_70.png" /> Wai Hawaila<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_71.png" /> Wai Hayako<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_72.png" /> Wai Heru<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_73.png" /> Wai Hiaite<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_74.png" /> Wai Hiko<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_75.png" /> Wai Hina<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_76.png" /> Wai Hinea<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_77.png" /> Wai Hisi<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_78.png" /> Wai Hitamputih<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_79.png" /> Wai Hitaputih<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_80.png" /> Wai Holai<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_81.png" /> Wai Htana<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_82.png" /> Wai Htatanam<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_83.png" /> Wai Htatu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_84.png" /> Wai Htile<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_85.png" /> Wai Htua<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_86.png" /> Wai Hululohu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_87.png" /> Wai Hulung<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_88.png" /> Wai Humuna<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_89.png" /> Wai Hunsel<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_90.png" /> Wai Husulu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_91.png" /> Wai Ife<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_92.png" /> Wai Ila<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_93.png" /> Wai Ilai<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_94.png" /> Wai Ile<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_95.png" /> Wai Imli<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_96.png" /> Wai Ino<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_97.png" /> Wai Isabana<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_98.png" /> Wai Isaka<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_99.png" /> Wai Isakau<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_100.png" /> Wai Isal<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_101.png" /> Wai Isiane<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_102.png" /> Wai Iweli<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_103.png" /> Wai Iyu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_104.png" /> Wai Jabulu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_105.png" /> Wai Jaha<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_106.png" /> Wai Jaluna<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_107.png" /> Wai Jamina<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_108.png" /> Wai Jana<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_109.png" /> Wai Japuwe<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_110.png" /> Wai Jeputih<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_111.png" /> Wai Jiwasihi<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_112.png" /> Wai Joko<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_113.png" /> Wai Juma<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_114.png" /> Wai Kaba<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_115.png" /> Wai Kaka<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_116.png" /> Wai Kakau<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_117.png" /> Wai Kakisapalewa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_118.png" /> Wai Kalahula<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_119.png" /> Wai Kalapori<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_120.png" /> Wai Kalaun<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_121.png" /> Wai Kannate<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_122.png" /> Wai Kara<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_123.png" /> Wai Karusoni<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_124.png" /> Wai Kawa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_125.png" /> Wai Kekeita<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_126.png" /> Wai Kiki<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_127.png" /> Wai Kilau<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_128.png" /> Wai Kira<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_129.png" /> Wai Kobi<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_130.png" /> Wai Kobisontah<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_131.png" /> Wai Kokouwe<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_132.png" /> Wai Kuhu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_133.png" /> Wai Kuku<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_134.png" /> Wai Kumabakalan<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_135.png" /> Wai Kumula<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_136.png" /> Wai Kuwa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_137.png" /> Wai Lae<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_138.png" /> Wai Lahatan<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_139.png" /> Wai Lahatan Tua<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_140.png" /> Wai Lahatuntora<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_141.png" /> Wai Lakap<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_142.png" /> Wai Lalahulu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_143.png" /> Wai Lalan<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_144.png" /> Wai Lalao<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_145.png" /> Wai Lao<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_146.png" /> Wai Lapia<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_147.png" /> Wai Lapo<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_148.png" /> Wai Laputih<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_149.png" /> Wai Laritupate<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_150.png" /> Wai Lasu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_151.png" /> Wai Lata<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_152.png" /> Wai Lau Suanggi<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_153.png" /> Wai Leleru<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_154.png" /> Wai Lesa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_155.png" /> Wai Lesin<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_156.png" /> Wai Liahte<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_157.png" /> Wai Lial<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_158.png" /> Wai Lialiuse<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_159.png" /> Wai Libane<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_160.png" /> Wai Liboli<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_161.png" /> Wai Lil<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_162.png" /> Wai Liliboi<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_163.png" /> Wai Lla<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_164.png" /> Wai Lli<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_165.png" /> Wai Lofin<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_166.png" /> Wai Loi<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_167.png" /> Wai Loning<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_168.png" /> Wai Luka<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_169.png" /> Wai Mah<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_170.png" /> Wai Mahina<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_171.png" /> Wai Mahtaki<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_172.png" /> Wai Mahtam<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_173.png" /> Wai Maimual<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_174.png" /> Wai Makariki<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_175.png" /> Wai Makela<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_176.png" /> Wai Makilan<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_177.png" /> Wai Makina<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_178.png" /> Wai Mala<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_179.png" /> Wai Malaku<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_180.png" /> Wai Malawa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_181.png" /> Wai Maliuhtu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_182.png" /> Wai Mamala<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_183.png" /> Wai Mamua<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_184.png" /> Wai Man<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_185.png" /> Wai Mapilu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_186.png" /> Wai Marakee<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_187.png" /> Wai Marasahua<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_188.png" /> Wai Marduwe<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_189.png" /> Wai Mari<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_190.png" /> Wai Masbait<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_191.png" /> Wai Masin<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_192.png" /> Wai Masloi<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_193.png" /> Wai Mawoti<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_194.png" /> Wai Mee<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_195.png" /> Wai Mere<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_196.png" /> Wai Mesa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_197.png" /> Wai Meseng<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_198.png" /> Wai Metkita<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_199.png" /> Wai Metlime<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_200.png" /> Wai Mika<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_201.png" /> Wai Mila<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_202.png" /> Wai Minim<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_203.png" /> Wai Mintola<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_204.png" /> Wai Mitihu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_205.png" /> Wai Mocim<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_206.png" /> Wai Mohti<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_207.png" /> Wai Moli<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_208.png" /> Wai Molo<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_209.png" /> Wai Momokani<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_210.png" /> Wai Mowa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_211.png" /> Wai Mual<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_212.png" /> Wai Mual Kecil<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_213.png" /> Wai Mui<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_214.png" /> Wai Mula<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_215.png" /> Wai Mulau<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_216.png" /> Wai Mumun<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_217.png" /> Wai Muna<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_218.png" /> Wai Musae<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_219.png" /> Wai Musal<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_220.png" /> Wai Musi<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_221.png" /> Wai Musiana<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_222.png" /> Wai Musio<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_223.png" /> Wai Naka<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_224.png" /> Wai Nakupia<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_225.png" /> Wai Nalawai<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_226.png" /> Wai Nama<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_227.png" /> Wai Nama Dua<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_228.png" /> Wai Namana<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_229.png" /> Wai Namasula<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_230.png" /> Wai Namtina<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_231.png" /> Wai Namto<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_232.png" /> Wai Napuru<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_233.png" /> Wai Nari<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_234.png" /> Wai Narsu Laku<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_235.png" /> Wai Nata<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_236.png" /> Wai Nau<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_237.png" /> Wai Nia<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_238.png" /> Wai Niniana<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_239.png" /> Wai Ninus<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_240.png" /> Wai Niu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_241.png" /> Wai Nolere<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_242.png" /> Wai Nota<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_243.png" /> Wai Nua<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_244.png" /> Wai Nunubuwet<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_245.png" /> Wai Nuti<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_246.png" /> Wai Nyaka<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_247.png" /> Wai Olami<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_248.png" /> Wai One<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_249.png" /> Wai Oni<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_250.png" /> Wai Orowana<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_251.png" /> Wai Oto<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_252.png" /> Wai Pakota<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_253.png" /> Wai Palapin<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_254.png" /> Wai Palau<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_255.png" /> Wai Paliosi<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_256.png" /> Wai Palu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_257.png" /> Wai Panowelo<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_258.png" /> Wai Parol<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_259.png" /> Wai Patal<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_260.png" /> Wai Paumahu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_261.png" /> Wai Pelea<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_262.png" /> Wai Pendeta<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_263.png" /> Wai Pesuli<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_264.png" /> Wai Pia<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_265.png" /> Wai Pocona<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_266.png" /> Wai Pula<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_267.png" /> Wai Pulin<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_268.png" /> Wai Puoru<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_269.png" /> Wai Pute<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_270.png" /> Wai Putih<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_271.png" /> Wai Ralau<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_272.png" /> Wai Raras<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_273.png" /> Wai Riori<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_274.png" /> Wai Roisi<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_275.png" /> Wai Ruata<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_276.png" /> Wai Sahalu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_277.png" /> Wai Sahtalai<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_278.png" /> Wai Sahtol<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_279.png" /> Wai Sahtua<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_280.png" /> Wai Sai<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_281.png" /> Wai Saka<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_282.png" /> Wai Sakula<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_283.png" /> Wai Sala<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_284.png" /> Wai Sala Dua<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_285.png" /> Wai Sala Tiga<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_286.png" /> Wai Salaguga<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_287.png" /> Wai Salah<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_288.png" /> Wai Salaita<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_289.png" /> Wai Salalu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_290.png" /> Wai Salawa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_291.png" /> Wai Salawai<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_292.png" /> Wai Saleb<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_293.png" /> Wai Sama<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_294.png" /> Wai Samal<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_295.png" /> Wai Samanuwa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_296.png" /> Wai Samsu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_297.png" /> Wai Sanakoraka<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_298.png" /> Wai Sanese<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_299.png" /> Wai Sanue<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_300.png" /> Wai Saowe<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_301.png" /> Wai Sapalewa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_302.png" /> Wai Sapalewu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_303.png" /> Wai Sapolose<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_304.png" /> Wai Sapotena<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_305.png" /> Wai Sarapak<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_306.png" /> Wai Sare<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_307.png" /> Wai Sariputih<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_308.png" /> Wai Sariputih Kecil<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_309.png" /> Wai Satu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_310.png" /> Wai Saunulu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_311.png" /> Wai Sayah<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_312.png" /> Wai Sela<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_313.png" /> Wai Selemanata<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_314.png" /> Wai Seli<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_315.png" /> Wai Seliha<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_316.png" /> Wai Sewa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_317.png" /> Wai Sia<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_318.png" /> Wai Siatele<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_319.png" /> Wai Sidel<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_320.png" /> Wai Sieti<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_321.png" /> Wai Sika<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_322.png" /> Wai Sikabul<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_323.png" /> Wai Sikapate<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_324.png" /> Wai Sila<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_325.png" /> Wai Silahta<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_326.png" /> Wai Silati<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_327.png" /> Wai Silawa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_328.png" /> Wai Silete<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_329.png" /> Wai Simuhta<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_330.png" /> Wai Sina<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_331.png" /> Wai Sinado<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_332.png" /> Wai Sinlari<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_333.png" /> Wai Siriukuna<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_334.png" /> Wai Sisonya<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_335.png" /> Wai Sisulai<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_336.png" /> Wai Sitetu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_337.png" /> Wai Sivat<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_338.png" /> Wai Soju<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_339.png" /> Wai Solok<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_340.png" /> Wai Sonam<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_341.png" /> Wai Sonia<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_342.png" /> Wai Sonoyoto<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_343.png" /> Wai Soqalala<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_344.png" /> Wai Sorolowa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_345.png" /> Wai Sosonatuota<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_346.png" /> Wai Sou<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_347.png" /> Wai Suk<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_348.png" /> Wai Sukama<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_349.png" /> Wai Sunemaikuh<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_350.png" /> Wai Suru<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_351.png" /> Wai Suwoni<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_352.png" /> Wai Tabo<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_353.png" /> Wai Talafata<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_354.png" /> Wai Tale<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_355.png" /> Wai Tali<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_356.png" /> Wai Talohereta<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_357.png" /> Wai Tamalaya<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_358.png" /> Wai Tani<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_359.png" /> Wai Tanjungleci<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_360.png" /> Wai Tanru<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_361.png" /> Wai Tantu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_362.png" /> Wai Tanusang<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_363.png" /> Wai Tasilaha<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_364.png" /> Wai Tatiri<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_365.png" /> Wai Tatumaune<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_366.png" /> Wai Tawelasunya<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_367.png" /> Wai Taya<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_368.png" /> Wai Tengah<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_369.png" /> Wai Tepuo<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_370.png" /> Wai Ternate<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_371.png" /> Wai Teui<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_372.png" /> Wai Tihtupana<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_373.png" /> Wai Tila<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_374.png" /> Wai Timoya<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_375.png" /> Wai Tina<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_376.png" /> Wai Tinupa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_377.png" /> Wai Tiu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_378.png" /> Wai Toa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_379.png" /> Wai Tobi<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_380.png" /> Wai Tofuluwe<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_381.png" /> Wai Tohisa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_382.png" /> Wai Toko<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_383.png" /> Wai Tolohil<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_384.png" /> Wai Tolomoni<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_385.png" /> Wai Toluarang<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_386.png" /> Wai Toluran<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_387.png" /> Wai Tomojaharni<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_388.png" /> Wai Tomonahunse<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_389.png" /> Wai Tomu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_390.png" /> Wai Tonahitu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_391.png" /> Wai Tonalopa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_392.png" /> Wai Tonetanah<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_393.png" /> Wai Tonosai<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_394.png" /> Wai Toto<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_395.png" /> Wai Totun<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_396.png" /> Wai Trihea<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_397.png" /> Wai Tui<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_398.png" /> Wai Tun<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_399.png" /> Wai Uawai<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_400.png" /> Wai Ula-Ula<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_401.png" /> Wai Ulakaba<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_402.png" /> Wai Ule<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_403.png" /> Wai Ulupa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_404.png" /> Wai Umai Putih<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_405.png" /> Wai Umu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_406.png" /> Wai Una<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_407.png" /> Wai Unana<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_408.png" /> Wai Upa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_409.png" /> Wai Upolo<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_410.png" /> Wai Urak<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_411.png" /> Wai Uta<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_412.png" /> Wai Utu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_413.png" /> Wai Uwa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_414.png" /> Wai Uwao<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_415.png" /> Wai Vowairi<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_416.png" /> Wai Waai<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_417.png" /> Wai Wababoake<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_418.png" /> Wai Wahatu Dua<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_419.png" /> Wai Wahatu Satu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_420.png" /> Wai Wahei<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_421.png" /> Wai Waikau<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_422.png" /> Wai Waiso<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_423.png" /> Wai Waka<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_424.png" /> Wai Wakabakepa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_425.png" /> Wai Wakajesea<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_426.png" /> Wai Wakanu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_427.png" /> Wai Wakasihu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_428.png" /> Wai Wakauli<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_429.png" /> Wai Wala<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_430.png" /> Wai Walala<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_431.png" /> Wai Walapu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_432.png" /> Wai Wale<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_433.png" /> Wai Walemutali<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_434.png" /> Wai Wali<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_435.png" /> Wai Wallo<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_436.png" /> Wai Wamsoiju<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_437.png" /> Wai Wanawa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_438.png" /> Wai Wanouna<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_439.png" /> Wai Waoase<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_440.png" /> Wai Wasa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_441.png" /> Wai Wasuna<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_442.png" /> Wai Watara<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_443.png" /> Wai Wauaoamawa<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_444.png" /> Wai Waulu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_445.png" /> Wai Wauteu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_446.png" /> Wai Wawaka<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_447.png" /> Wai Wawapote<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_448.png" /> Wai Waya<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_449.png" /> Wai Wayari<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_450.png" /> Wai Weatuu Besar<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_451.png" /> Wai Weatuu Kecil<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_452.png" /> Wai Wele<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_453.png" /> Wai Weliai<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_454.png" /> Wai Weyote<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_455.png" /> Wai Wisal<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_456.png" /> Wai Woka<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_457.png" /> Wai Wolu<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_458.png" /> Wai Yae<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_459.png" /> Wai Yaea<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_460.png" /> Wai Yala<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_461.png" /> Wai Yana<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_462.png" /> Wai Yanaanate<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_463.png" /> Wai Yani<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_464.png" /> Wai Yapana<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_465.png" /> Wai Yaputih<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_466.png" /> Wai Yau<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_467.png" /> Wai Yehte<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_468.png" /> Wai Yeyonima<br />\
    <img src="styles/legend/SUNGAI_LN_50K_3_469.png" /> Wai Yua<br />'
        });

lyr_OpenStreetMap_0.setVisible(true);lyr_ADMINISTRASIKECAMATAN_AR_50K_1.setVisible(true);lyr_SARANAIBADAH_PT_50K_2.setVisible(true);lyr_SUNGAI_LN_50K_3.setVisible(true);
var layersList = [lyr_OpenStreetMap_0,lyr_ADMINISTRASIKECAMATAN_AR_50K_1,lyr_SARANAIBADAH_PT_50K_2,lyr_SUNGAI_LN_50K_3];
lyr_ADMINISTRASIKECAMATAN_AR_50K_1.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', });
lyr_SARANAIBADAH_PT_50K_2.set('fieldAliases', {'NAMOBJ': 'NAMOBJ', 'LUAS': 'LUAS', 'FGSIBD': 'FGSIBD', 'FCODE': 'FCODE', 'REMARK': 'REMARK', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', });
lyr_SUNGAI_LN_50K_3.set('fieldAliases', {'NAMOBJ': 'NAMOBJ', 'TIPSNG': 'TIPSNG', 'KLSSNG': 'KLSSNG', 'FCODE': 'FCODE', 'REMARK': 'REMARK', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'NAMWS': 'NAMWS', 'NAMDAS': 'NAMDAS', 'STATUS': 'STATUS', 'WMAX': 'WMAX', 'DBTMAX': 'DBTMAX', 'SLPRT': 'SLPRT', 'SHAPE_Leng': 'SHAPE_Leng', });
lyr_ADMINISTRASIKECAMATAN_AR_50K_1.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', });
lyr_SARANAIBADAH_PT_50K_2.set('fieldImages', {'NAMOBJ': 'TextEdit', 'LUAS': 'TextEdit', 'FGSIBD': 'TextEdit', 'FCODE': 'TextEdit', 'REMARK': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', });
lyr_SUNGAI_LN_50K_3.set('fieldImages', {'NAMOBJ': 'TextEdit', 'TIPSNG': 'TextEdit', 'KLSSNG': 'TextEdit', 'FCODE': 'TextEdit', 'REMARK': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'NAMWS': 'TextEdit', 'NAMDAS': 'TextEdit', 'STATUS': 'TextEdit', 'WMAX': 'TextEdit', 'DBTMAX': 'TextEdit', 'SLPRT': 'TextEdit', 'SHAPE_Leng': 'TextEdit', });
lyr_ADMINISTRASIKECAMATAN_AR_50K_1.set('fieldLabels', {'KDPPUM': 'no label', 'NAMOBJ': 'no label', 'REMARK': 'no label', 'KDPBPS': 'no label', 'FCODE': 'no label', 'LUASWH': 'no label', 'UUPP': 'no label', 'SRS_ID': 'no label', 'LCODE': 'no label', 'METADATA': 'no label', 'KDEBPS': 'no label', 'KDEPUM': 'no label', 'KDCBPS': 'no label', 'KDCPUM': 'no label', 'KDBBPS': 'no label', 'KDBPUM': 'no label', 'WADMKD': 'no label', 'WIADKD': 'no label', 'WADMKC': 'no label', 'WIADKC': 'no label', 'WADMKK': 'no label', 'WIADKK': 'no label', 'WADMPR': 'no label', 'WIADPR': 'no label', 'TIPADM': 'no label', 'SHAPE_Leng': 'no label', 'SHAPE_Area': 'no label', });
lyr_SARANAIBADAH_PT_50K_2.set('fieldLabels', {'NAMOBJ': 'no label', 'LUAS': 'no label', 'FGSIBD': 'no label', 'FCODE': 'no label', 'REMARK': 'no label', 'SRS_ID': 'no label', 'LCODE': 'no label', 'METADATA': 'no label', });
lyr_SUNGAI_LN_50K_3.set('fieldLabels', {'NAMOBJ': 'no label', 'TIPSNG': 'no label', 'KLSSNG': 'no label', 'FCODE': 'no label', 'REMARK': 'no label', 'SRS_ID': 'no label', 'LCODE': 'no label', 'METADATA': 'no label', 'NAMWS': 'no label', 'NAMDAS': 'no label', 'STATUS': 'no label', 'WMAX': 'no label', 'DBTMAX': 'no label', 'SLPRT': 'no label', 'SHAPE_Leng': 'no label', });
lyr_SUNGAI_LN_50K_3.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});